PerformanC/ReZygisk

.github/ISSUE_TEMPLATE/issue_template.yml, .github/ISSUE_TEMPLATE/pull_request.yml, .github/PULL_REQUEST_TEMPLATE.md
This commit will add new issue, FR, PR template for github
Convenient for user who wants to contribute and feature request
nil
=> add: issue, FR, PR github template

webroot/js/lang/index.js, webroot/js/lang/ro_RO.js
This PR adds support for the ro_RO: Română (România) language
It would make the application more accessible to native speakers of this language.
=> Introduce ro_RO language

webroot/js/language.js, webroot/lang/ja_JP.json
Added Japanese translation
Because I was asked to do so lol
=> add: Japanese translation (ja_JP.json)

webroot/js/main.js
Write here why you think this should be merged
- [*] The modified functions have been tested.
- [*] Used the same indentation as the rest of the project.
=> fix #36: WebUI not working on 64 bit only devices

webroot/js/language.js, webroot/lang/zh_CN.json
Translate all currently existing English strings to Chinese.
Translation work.
- The modified functions have been tested.
- Used the same indentation as the rest of the project.
- Updated documentation (changelog).
Nothing additional, just translation.
=> Full Chinese Translation.

webroot/css/index.css, webroot/js/main.js
Fix a bug of module string analyzing. (lines[ ] was not declared)
Formatting Code using prettier.
Bug fixes.
[ ] The modified functions have been tested.
[ ] Used the same indentation as the rest of the project.
[ ] Updated documentation (changelog).
Rainy should know the issue.
I've tested my edit already.
=> Fix a bug of module string analyzing, style improvement of small card and Header

README.md
- added badges at the start of the repo by (Releases, License, Localization, Nightly Release (Actions), Issues Amount, Pull Request Amount, Discord and Telegram Channel links)
- added more details about the dependencies.
- rewrite some sentences to be more concise.
- Added more detail to the note (talk about unstable release can found in Action page but only install at discretion).
- To prepare for the release of the project to the public.
=> improve: README.md

README_CN.md
Update the license information in the Chinese README based on the English README.
Update the BSD 2-Clause License in the Chinese README to the AGPL-3.0 License.
The license information has been updated in the English version.
=> update:  Update the license information in the Chinese README.

README.md, README_CN.md
Fix Readme link error
No why :)
A small change.
=> Fix readme link error

TRANSLATOR.md, webroot/lang/id_ID.json
Add Indonesian language for WebUI
=> Add Indonesian language for WebUI

TRANSLATOR.md, webroot/lang/tr_TR.json
added a Turkish translation for the WebUI
why not
- [  ] The modified functions have been tested.
unfortunately can't test at the moment, used en_US.json as a base. if there's anything wrong please let me know, will be happy to help further!
=> add: Turkish (tr_TR) language for WebUI

READMEs/README_ja-JP.md
JP ReadMe
Adding another lang for README is always good
=> Translation: Added README-ja_JP.md

TRANSLATOR.md, webroot/lang/id_ID.json
This commit updates the translations for indonesia with the proper grammar
=> update: translations for id_ID

README.md, READMEs/README_id-ID.md
This commit adds indonesia translation for README.
=> add: README_id-id.md 

README.md, READMEs/README_vi-VN.md
Add vietnamese translation for README
For easier to explain to Vietnamese people why this project exist
=> add: translated to vietnamese README

README.md, READMEs/README_tr-TR.md
Add Turkish translation for README
Add Turkish to the Readme
=> add: Turkish README.md

loader/src/common/dl.cpp, loader/src/common/files.cpp, loader/src/include/files.hpp, loader/src/injector/hook.cpp, zygiskd/src/zygiskd.c
Move away from using memfd because it does not exist on old android versions.
=> Support Android 9

loader/src/injector/gen_jni_hooks.py, loader/src/injector/jni_hooks.hpp
fix zygisk failing on grapheneos
same as the title
=> fix zygisk failing on grapheneos

TRANSLATOR.md
Fix TRANSLATOR.md 
Fix TRANSLATOR.md
=> Fix TRANSLATOR.md 

TRANSLATOR.md, webroot/lang/ar_EG.json
- Added Arabic translation to WebUI
- I'd like to contribute to ReZygisk by any form of help, so I decided to help in WebUI translation, and translated strings into Arabic language.
=> feat: Added Arabic Translation

TRANSLATOR.md, webroot/lang/it_IT.json
Italian translations
For the italian speakers
- [✅] The modified functions have been tested.
- [✅] Used the same indentation as the rest of the project.
- [❌] Updated documentation (changelog).
I'm not sure about why there's so many commits which aren't made by me, hope it's not a problem because i don't know how to remove them. EDIT: i think i got rid of it
=> Italian translations

webroot/lang/id_ID.json
This commit updates Indonesian translations.
To pass a better clarity about the information, some Indonesian translations were updated.
=> Improve WebUI Indonesian translation
